server:
  port: 8086
  
spring:
  application:
    name: auth-api
  datasource:
    #url: jdbc:h2:mem:authdb
    url: jdbc:mysql://localhost:3360/test_auth_api?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  # Configuration SMTP pour l'envoi d'emails
  mail:
    # Configuration SMTP à adapter avec vos informations
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: xxxx
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    
security:
  jwt:
    token:
      secret-key: 7133743677397A24432646294A404E635266556A586E327235753878214125442A472D4B6150645367566B5970337336763979244226452948404D6351655468
      expiration-time: 86400000 # 24 heures en millisecondes

# Configuration pour l'application
app:
  # URL de base de l'application frontend pour les liens dans les emails
  frontend-url: http://localhost:8086
  # Expéditeur des emails
  email-from: noreply@votredomaine.com
  # Nom de l'expéditeur
  email-from-name: "Votre Application"